import type { Metadata } from "next";
import { Inter, ABeeZee } from "next/font/google";
import "./globals.css";

// import NavLinks from "../ui/nav-links";

// const inter = Inter({ subsets: ["latin"], display: "swap" });
const abeezee = ABeeZee({ subsets: ["latin"], display: "swap", weight: "400" });

export const metadata: Metadata = {
  title: "Home | PortRadar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abeezee.className}>
        {/* <NavLinks /> */}
        {children}
      </body>
    </html>
  );
}
